locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }
source "amazon-ebs" "autogenerated_1" {
#  access_key    = "${var.aws_access_key}"
  ami_name      = "packer-example ${local.timestamp}"
  instance_type = "t2.micro"
  region        = "us-east-1"
#  secret_key    = "${var.aws_secret_key}"
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"]
  }
  ssh_username = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "packer-test-file"
  }
  provisioner "shell" {
    inline = ["ls -al /home/ubuntu", "cat /home/ubuntu/packer-test-file"]
  }
  provisioner "shell" {
    script = "./myscript.sh"
  }
}
